#!/bin/bash
echo "Program starting"
echo "----------arrayparam----------"
time java -jar ./antlr/iopt.jar ./input/arrayparam.il
java -jar iloc.jar -s ./input/arrayparam.il > ./output/arrayparam.out
java -jar iloc.jar -s ./input/arrayparam.iopt.il > ./output/arrayparam.iopt.out
diff ./output/arrayparam.out ./output/arrayparam.iopt.out
echo "------------------------------"
echo "------------bubble------------"
time java -jar ./antlr/iopt.jar ./input/bubble.il
java -jar iloc.jar -s ./input/bubble.il > ./output/bubble.out
java -jar iloc.jar -s ./input/bubble.iopt.il > ./output/bubble.iopt.out
diff ./output/bubble.out ./output/bubble.iopt.out
echo "------------------------------"
echo "------------check-------------"
time java -jar ./antlr/iopt.jar ./input/check.il
java -jar iloc.jar -s ./input/check.il > ./output/check.out
java -jar iloc.jar -s ./input/check.iopt.il > ./output/check.iopt.out
diff ./output/check.out ./output/check.iopt.out
echo "------------------------------"
echo "-----------dynamic------------"
time java -jar ./antlr/iopt.jar ./input/dynamic.il
java -jar iloc.jar -s ./input/dynamic.il > ./output/dynamic.out
java -jar iloc.jar -s ./input/dynamic.iopt.il > ./output/dynamic.iopt.out
diff ./output/dynamic.out ./output/dynamic.iopt.out
echo "------------------------------"
echo "-------------fib--------------"
time java -jar ./antlr/iopt.jar ./input/fib.il
java -jar iloc.jar -s ./input/fib.il > ./output/fib.out
java -jar iloc.jar -s ./input/fib.iopt.il > ./output/fib.iopt.out
diff ./output/fib.out ./output/fib.iopt.out
echo "------------------------------"
echo "--------------gcd-------------"
time java -jar ./antlr/iopt.jar ./input/gcd.il < ./input/gcd.in
java -jar iloc.jar -s ./input/gcd.il < ./input/gcd.in > ./output/gcd.out
java -jar iloc.jar -s ./input/gcd.iopt.il < ./input/gcd.in > ./output/gcd.iopt.out
diff ./output/gcd.out ./output/gcd.iopt.out
echo "------------------------------"
echo "------------newdyn------------"
time java -jar ./antlr/iopt.jar ./input/newdyn.il
java -jar iloc.jar -s ./input/newdyn.il > ./output/newdyn.out
java -jar iloc.jar -s ./input/newdyn.iopt.il > ./output/newdyn.iopt.out
diff ./output/newdyn.out ./output/newdyn.iopt.out
echo "------------------------------"
echo "--------------qs--------------"
time java -jar ./antlr/iopt.jar ./input/qs.il < ./input/qs.in
java -jar iloc.jar -s ./input/qs.il < ./input/qs.in > ./output/qs.out
java -jar iloc.jar -s ./input/qs.iopt.il < ./input/qs.in  > ./output/qs.iopt.out
diff ./output/qs.out ./output/qs.iopt.out
echo "------------------------------"
echo "---------while_array----------"
time java -jar ./antlr/iopt.jar ./input/while_array.il
java -jar iloc.jar -s ./input/while_array.il > ./output/while_array.out
java -jar iloc.jar -s ./input/while_array.iopt.il > ./output/while_array.iopt.out
diff ./output/while_array.out ./output/while_array.iopt.out
echo "Done."